server:
  port: 8081

spring:
  application:
    name: central-auth-service
  cloud:
    compatibility-verifier:
      enabled: false
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@{ip}:{port}:{serviceName}
    username: NGA
    password: NGA
    hikari:
      connection-timeout: 10000
      maximum-pool-size: 30

management:
  endpoints:
    web:
      exposure:
        include: info, health, env

eureka:
  client:
    enabled: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

jwt:
  securityTokenBag:
    CREATE_CUSTOMER_PROFILE:
      secretKey: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
      expirationTime: 600000
    ACCESS_BL_SERVICE:
      secretKey: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
      expirationTime: 600000

springdoc:
  swagger-ui:
    enabled: true