server:
  port: 8082

spring:
  application:
    name: create-customer-profile
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@{ip}:{port}:{serviceName}
    username: NGA
    password: NGA
    hikari:
      connection-timeout: 1000
      maximum-pool-size: 30
  cloud:
    compatibility-verifier:
      enabled: false

eureka:
  client:
    enabled: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: info, health, env

jwt:
  secretKey: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b

springdoc:
  swagger-ui:
    enabled: true
