server:
  port: 8082

spring:
  application:
    name: create-customer-profile
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@{ip}:{port}:{serviceName}
    username: username
    password: password
    hikari:
      connection-timeout: 1000
      maximum-pool-size: 30
  cloud:
    compatibility-verifier:
      enabled: false

eureka:
  client:
    enabled: true
    register-with-eureka: true
    service-url:
      #defaultZone: http://localhost:8761/eureka  #This line is used when running as a stand-alone spring boot service
      defaultZone: http://eureka-server:8761/eureka #This line is used when running as a docker container. Using Eureka server container name i.e., eureka-server instead of local host

management:
  endpoints:
    web:
      exposure:
        include: info, health, env

jwt:
  secretKey: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b

springdoc:
  swagger-ui:
    enabled: true

logging:
  file:
    name: /logs/create-customer-profile-service.log