server:
  port: 8080

spring:
  application:
    name: governing-state
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@{ip}:{port}:{serviceName}
    username: NGA
    password: NGA
    hikari:
      connection-timeout: 10000
      maximum-pool-size: 25
  redis:
    host: localhost
    port: 6379
  cloud:
    compatibility-verifier:
      enabled: false

management:
  endpoints:
    web:
      exposure:
        include: info, health, env

eureka:
  client:
    enabled: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

application:
  caches:
    default:
      time-to-live: 30000
      key-prefix: default-
      use-key-prefix: true
    governing-state:
      time-to-live: 60000
      key-prefix: governing-state-
      use-key-prefix: true